version: "3.7"

services:
    database:
        image: postgres:alpine
        container_name: ${APP_NAME}-database-${APP_ENV}
        env_file:
            - ./.env
        # ports:
        #     - 5432:5432
        environment:
            - POSTGRES_USER=goals-web-user
            - POSTGRES_PASSWORD=test
        volumes:
            - goalsdata:/var/lib/postgresql/data
        restart: always

volumes:
    goalsdata:
